# Generated by Django 3.2.15 on 2022-08-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220816_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='timestamp',
        ),
    ]
